#!/bin/sh

# Must be sourced on startup of a login shell, after $XDG_CONFIG_HOME/shell/env
# Should not change the shell env

command -v 'fortune' > /dev/null && command -v 'cowsay' > /dev/null &&
    fortune "${XDG_DATA_HOME:-"$HOME/.local/share"}/fortune" |
        cowsay -f 'tux' -n
    # Personal fortunes

